#!/bin/bash

jupyter nbconvert notebooks/2022-03-20-survey-pipeline-1.ipynb --to html --output ../_posts/drafts/2022-03-20-survey-pipeline-1.html

jupyter nbconvert notebooks/2022-03-26-survey-pipeline-2.ipynb --to html --output ../_posts/drafts/2022-03-26-survey-pipeline-2.html

jupyter nbconvert notebooks/2022-03-26-survey-pipeline-3.ipynb --to html --output ../_posts/drafts/2022-03-26-survey-pipeline-3.html
