#!/bin/bash

# Note: Before running this script,
#  1) If you downloaded the notebook from Google Colab, replace file name underscores with hyphens
#  2) If you want to embed an image in the notebook,
#     a) Set up Markdown cell with <img src="" />
#     b) Convert image to Base64 at https://www.base64-image.de/ (can be JPG, PNG, GIF, WebP, SVG or BMP, up to 1MB)
#     c) Paste the output (starting with data:image/) into the quotes in the img tag
#  2) Change the name of the notebook (input) and markdown (output) files below
#  3) Save this script

# Run this script in the terminal using ./nb_md

jupyter nbconvert _notebooks/2022-12-18-Visualizing-Nonbinary-Trees-Classification-of-Chemical-Isomers.ipynb --to markdown --output 2022-12-18-Visualizing-Nonbinary-Trees-Classification-of-Chemical-Isomers.md

# Note: After running this script, to post a blog post:
#  1) Move the markdown file into the _posts folder
#  2) Move the _files folder (containing the images) into the images folder
#  3) Fix the image links in the markdown file by converting e.g.
#          ![png](2022-11-11-RDKit-Recap-decomposition-tree_files/2022-11-11-RDKit-Recap-decomposition-tree_10_0.png)
#      to
#         ![png](/images/2022-11-11-RDKit-Recap-decomposition-tree_files/2022-10-09-RDKit-find-and-highlight-the-maximum-common-substructure-between-molecules_24_0.png)
#      by replacing
#         ![png](
#      with
#         ![png](/images/